{
 "title": "System metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1min",
     "column": "min1",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "misc",
     "query": "SELECT mean(\"min1\") FROM \"localhost.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "load_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "target": "randomWalk('random walk')"
    },
    {
     "alias": "5mins",
     "column": "min5",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "misc",
     "query": "SELECT mean(\"min5\") FROM \"localhost.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "load_5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load"
    },
    {
     "alias": "15mins",
     "column": "min15",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "misc",
     "query": "SELECT mean(\"min15\") FROM \"localhost.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "load_15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "misc",
     "query": "SELECT last(\"processes\") FROM \"misc\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "processes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "series": "processcount"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "misc",
     "query": "SELECT last(\"seconds\")  FROM \"localhost.uptime\" WHERE $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Current time", "type": "grafana-clock-panel", "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "CPU (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(/^cpu\\d+$/) FROM \"cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "/(cpu)\\d+/" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"used\") FROM \"localhost.mem\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem"
    },
    {
     "alias": "Max",
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"total\") FROM \"memory\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "RX Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netio",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "TX Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netio",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "/ Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "column": "\"/.used\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"/.used\") FROM \"localhost.fs\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "/_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs"
    },
    {
     "alias": "Max",
     "column": "\"/.size\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"/.size\") FROM \"localhost.fs\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "/_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Read",
     "column": "sda2.read_bytes",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT mean(\"sda2.read_bytes\")/mean(\"sda2.time_since_update\")*8 FROM \"localhost.diskio\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "diskio"
    },
    {
     "alias": "Write",
     "column": "sda2.write_bytes",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT mean(\"sda2.write_bytes\")/mean(\"sda2.time_since_update\")*8 FROM \"localhost.diskio\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "diskio"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "column": "\"/.percent\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"/.percent\") FROM \"localhost.fs\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "column": "\"/.percent\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"/.percent\") FROM \"localhost.fs\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "/_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs"
    }
   ]
  },
  {
   "title": "GPU utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "core usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia",
     "select": [
      [
       { "params": [ "gpu_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gpu", "operator": "=", "value": "uuid_here" }
     ]
    },
    {
     "alias": "memory bandwidth usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia",
     "select": [
      [
       { "params": [ "mem_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gpu", "operator": "=", "value": "uuid_here" }
     ]
    }
   ]
  },
  {
   "title": "GPU memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia",
     "select": [
      [
       { "params": [ "mem_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gpu", "operator": "=", "value": "uuid_here" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia",
     "select": [
      [
       { "params": [ "mem_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gpu", "operator": "=", "value": "uuid_here" }
     ]
    }
   ]
  },
  { "title": "CPU details", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU user",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "min",
     "column": "system",
     "function": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT min(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "max",
     "column": "system",
     "function": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "mean_shade",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "CPU system",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "min",
     "column": "system",
     "function": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT min(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "max",
     "column": "system",
     "function": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "mean_shade",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "min",
     "column": "system",
     "function": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT min(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "max",
     "column": "system",
     "function": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "mean_shade",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "CPU nice",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "min",
     "column": "system",
     "function": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT min(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "max",
     "column": "system",
     "function": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "mean_shade",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "CPU irq",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "min",
     "column": "system",
     "function": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT min(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "irq" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "max",
     "column": "system",
     "function": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "irq" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "mean_shade",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "CPU softirq",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "min",
     "column": "system",
     "function": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT min(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "softirq" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "max",
     "column": "system",
     "function": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "softirq" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "mean_shade",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "Context switches",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"ctx_switches\") / mean(\"time_since_update\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "ctx_switches" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "min",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"ctx_switches\") / mean(\"time_since_update\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "ctx_switches" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "max",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"ctx_switches\") / mean(\"time_since_update\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "ctx_switches" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "mean_shade",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"ctx_switches\") / mean(\"time_since_update\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "ctx_switches" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"ctx_switches\") / mean(\"time_since_update\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "interrupts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "min",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"ctx_switches\") / mean(\"time_since_update\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "interrupts" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "max",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"ctx_switches\") / mean(\"time_since_update\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "interrupts" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "mean_shade",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"ctx_switches\") / mean(\"time_since_update\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "interrupts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  { "title": "Sensors", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }, "content": "# title" },
  {
   "title": "CPU temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "cpu_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU frequency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(/cpu\\d+_freq/) FROM \"cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU temperature / fanspeed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gpu", "operator": "=", "value": "uuid_here" }
     ]
    },
    {
     "alias": "Fanspeed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia",
     "select": [
      [
       { "params": [ "fanspeed_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gpu", "operator": "=", "value": "uuid_here" }
     ]
    }
   ]
  },
  {
   "title": "GPU frequencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "core",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia",
     "select": [
      [
       { "params": [ "core_clock" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gpu", "operator": "=", "value": "uuid_here" }
     ]
    },
    {
     "alias": "memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia",
     "select": [
      [
       { "params": [ "mem_clock" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gpu", "operator": "=", "value": "uuid_here" }
     ]
    },
    {
     "alias": "core max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia",
     "select": [
      [
       { "params": [ "max_core_clock" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gpu", "operator": "=", "value": "uuid_here" }
     ]
    },
    {
     "alias": "memory max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia",
     "select": [
      [
       { "params": [ "max_mem_clock" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gpu", "operator": "=", "value": "uuid_here" }
     ]
    }
   ]
  },
  {
   "title": "GPU power usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia",
     "select": [
      [
       { "params": [ "power_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gpu", "operator": "=", "value": "uuid_here" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia",
     "select": [
      [
       { "params": [ "power_limit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gpu", "operator": "=", "value": "uuid_here" }
     ]
    }
   ]
  }
 ]
}